// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.25.8
// source: authstream.proto

package authstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataRequest) Reset() {
	*x = UserDataRequest{}
	mi := &file_authstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataRequest) ProtoMessage() {}

func (x *UserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataRequest.ProtoReflect.Descriptor instead.
func (*UserDataRequest) Descriptor() ([]byte, []int) {
	return file_authstream_proto_rawDescGZIP(), []int{0}
}

func (x *UserDataRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDataRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataResponse) Reset() {
	*x = UserDataResponse{}
	mi := &file_authstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResponse) ProtoMessage() {}

func (x *UserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResponse.ProtoReflect.Descriptor instead.
func (*UserDataResponse) Descriptor() ([]byte, []int) {
	return file_authstream_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_authstream_proto protoreflect.FileDescriptor

const file_authstream_proto_rawDesc = "" +
	"\n" +
	"\x10authstream.proto\x12\n" +
	"authstream\"I\n" +
	"\x0fUserDataRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x10UserDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xb0\x01\n" +
	"\x0fUserDataService\x12O\n" +
	"\x12VerifyUserPassword\x12\x1b.authstream.UserDataRequest\x1a\x1c.authstream.UserDataResponse\x12L\n" +
	"\x0fRegisterNewUser\x12\x1b.authstream.UserDataRequest\x1a\x1c.authstream.UserDataResponseB\x0eZ\f.;authstreamb\x06proto3"

var (
	file_authstream_proto_rawDescOnce sync.Once
	file_authstream_proto_rawDescData []byte
)

func file_authstream_proto_rawDescGZIP() []byte {
	file_authstream_proto_rawDescOnce.Do(func() {
		file_authstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authstream_proto_rawDesc), len(file_authstream_proto_rawDesc)))
	})
	return file_authstream_proto_rawDescData
}

var file_authstream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authstream_proto_goTypes = []any{
	(*UserDataRequest)(nil),  // 0: authstream.UserDataRequest
	(*UserDataResponse)(nil), // 1: authstream.UserDataResponse
}
var file_authstream_proto_depIdxs = []int32{
	0, // 0: authstream.UserDataService.VerifyUserPassword:input_type -> authstream.UserDataRequest
	0, // 1: authstream.UserDataService.RegisterNewUser:input_type -> authstream.UserDataRequest
	1, // 2: authstream.UserDataService.VerifyUserPassword:output_type -> authstream.UserDataResponse
	1, // 3: authstream.UserDataService.RegisterNewUser:output_type -> authstream.UserDataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authstream_proto_init() }
func file_authstream_proto_init() {
	if File_authstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authstream_proto_rawDesc), len(file_authstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authstream_proto_goTypes,
		DependencyIndexes: file_authstream_proto_depIdxs,
		MessageInfos:      file_authstream_proto_msgTypes,
	}.Build()
	File_authstream_proto = out.File
	file_authstream_proto_goTypes = nil
	file_authstream_proto_depIdxs = nil
}
