// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: authstream.proto

package authstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataRequest) Reset() {
	*x = UserDataRequest{}
	mi := &file_authstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataRequest) ProtoMessage() {}

func (x *UserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataRequest.ProtoReflect.Descriptor instead.
func (*UserDataRequest) Descriptor() ([]byte, []int) {
	return file_authstream_proto_rawDescGZIP(), []int{0}
}

func (x *UserDataRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDataRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	UserID        uint32                 `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDataResponse) Reset() {
	*x = UserDataResponse{}
	mi := &file_authstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResponse) ProtoMessage() {}

func (x *UserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResponse.ProtoReflect.Descriptor instead.
func (*UserDataResponse) Descriptor() ([]byte, []int) {
	return file_authstream_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UserDataResponse) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type UserRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRefreshTokenRequest) Reset() {
	*x = UserRefreshTokenRequest{}
	mi := &file_authstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefreshTokenRequest) ProtoMessage() {}

func (x *UserRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*UserRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_authstream_proto_rawDescGZIP(), []int{2}
}

func (x *UserRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserRefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRefreshTokenResponse) Reset() {
	*x = UserRefreshTokenResponse{}
	mi := &file_authstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefreshTokenResponse) ProtoMessage() {}

func (x *UserRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*UserRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_authstream_proto_rawDescGZIP(), []int{3}
}

func (x *UserRefreshTokenResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_authstream_proto protoreflect.FileDescriptor

const file_authstream_proto_rawDesc = "" +
	"\n" +
	"\x10authstream.proto\x12\n" +
	"authstream\"I\n" +
	"\x0fUserDataRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"B\n" +
	"\x10UserDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\rR\x06userID\">\n" +
	"\x17UserRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"2\n" +
	"\x18UserRefreshTokenResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xcd\x03\n" +
	"\x0fUserDataService\x12O\n" +
	"\x12VerifyUserPassword\x12\x1b.authstream.UserDataRequest\x1a\x1c.authstream.UserDataResponse\x12L\n" +
	"\x0fRegisterNewUser\x12\x1b.authstream.UserDataRequest\x1a\x1c.authstream.UserDataResponse\x12\\\n" +
	"\x0fSetRefreshToken\x12#.authstream.UserRefreshTokenRequest\x1a$.authstream.UserRefreshTokenResponse\x12]\n" +
	"\x10FindRefreshToken\x12#.authstream.UserRefreshTokenRequest\x1a$.authstream.UserRefreshTokenResponse\x12^\n" +
	"\x11UnsetRefreshToken\x12#.authstream.UserRefreshTokenRequest\x1a$.authstream.UserRefreshTokenResponseB\x0eZ\f.;authstreamb\x06proto3"

var (
	file_authstream_proto_rawDescOnce sync.Once
	file_authstream_proto_rawDescData []byte
)

func file_authstream_proto_rawDescGZIP() []byte {
	file_authstream_proto_rawDescOnce.Do(func() {
		file_authstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authstream_proto_rawDesc), len(file_authstream_proto_rawDesc)))
	})
	return file_authstream_proto_rawDescData
}

var file_authstream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_authstream_proto_goTypes = []any{
	(*UserDataRequest)(nil),          // 0: authstream.UserDataRequest
	(*UserDataResponse)(nil),         // 1: authstream.UserDataResponse
	(*UserRefreshTokenRequest)(nil),  // 2: authstream.UserRefreshTokenRequest
	(*UserRefreshTokenResponse)(nil), // 3: authstream.UserRefreshTokenResponse
}
var file_authstream_proto_depIdxs = []int32{
	0, // 0: authstream.UserDataService.VerifyUserPassword:input_type -> authstream.UserDataRequest
	0, // 1: authstream.UserDataService.RegisterNewUser:input_type -> authstream.UserDataRequest
	2, // 2: authstream.UserDataService.SetRefreshToken:input_type -> authstream.UserRefreshTokenRequest
	2, // 3: authstream.UserDataService.FindRefreshToken:input_type -> authstream.UserRefreshTokenRequest
	2, // 4: authstream.UserDataService.UnsetRefreshToken:input_type -> authstream.UserRefreshTokenRequest
	1, // 5: authstream.UserDataService.VerifyUserPassword:output_type -> authstream.UserDataResponse
	1, // 6: authstream.UserDataService.RegisterNewUser:output_type -> authstream.UserDataResponse
	3, // 7: authstream.UserDataService.SetRefreshToken:output_type -> authstream.UserRefreshTokenResponse
	3, // 8: authstream.UserDataService.FindRefreshToken:output_type -> authstream.UserRefreshTokenResponse
	3, // 9: authstream.UserDataService.UnsetRefreshToken:output_type -> authstream.UserRefreshTokenResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authstream_proto_init() }
func file_authstream_proto_init() {
	if File_authstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authstream_proto_rawDesc), len(file_authstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authstream_proto_goTypes,
		DependencyIndexes: file_authstream_proto_depIdxs,
		MessageInfos:      file_authstream_proto_msgTypes,
	}.Build()
	File_authstream_proto = out.File
	file_authstream_proto_goTypes = nil
	file_authstream_proto_depIdxs = nil
}
