// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: chatstream.proto

package chatstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chatstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type MessageTable struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderID       uint32                 `protobuf:"varint,1,opt,name=senderID,proto3" json:"senderID,omitempty"`
	SenderUsername string                 `protobuf:"bytes,2,opt,name=senderUsername,proto3" json:"senderUsername,omitempty"`
	ChatID         uint32                 `protobuf:"varint,3,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Time           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageTable) Reset() {
	*x = MessageTable{}
	mi := &file_chatstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTable) ProtoMessage() {}

func (x *MessageTable) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTable.ProtoReflect.Descriptor instead.
func (*MessageTable) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{1}
}

func (x *MessageTable) GetSenderID() uint32 {
	if x != nil {
		return x.SenderID
	}
	return 0
}

func (x *MessageTable) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *MessageTable) GetChatID() uint32 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

func (x *MessageTable) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageTable) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type ChatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatID        uint32                 `protobuf:"varint,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	ChatName      string                 `protobuf:"bytes,2,opt,name=chatName,proto3" json:"chatName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInfo) Reset() {
	*x = ChatInfo{}
	mi := &file_chatstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInfo) ProtoMessage() {}

func (x *ChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInfo.ProtoReflect.Descriptor instead.
func (*ChatInfo) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{2}
}

func (x *ChatInfo) GetChatID() uint32 {
	if x != nil {
		return x.ChatID
	}
	return 0
}

func (x *ChatInfo) GetChatName() string {
	if x != nil {
		return x.ChatName
	}
	return ""
}

type ChatListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatListRequest) Reset() {
	*x = ChatListRequest{}
	mi := &file_chatstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatListRequest) ProtoMessage() {}

func (x *ChatListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatListRequest.ProtoReflect.Descriptor instead.
func (*ChatListRequest) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{3}
}

type ChatListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatList      []*ChatInfo            `protobuf:"bytes,1,rep,name=ChatList,proto3" json:"ChatList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatListResponse) Reset() {
	*x = ChatListResponse{}
	mi := &file_chatstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatListResponse) ProtoMessage() {}

func (x *ChatListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatListResponse.ProtoReflect.Descriptor instead.
func (*ChatListResponse) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{4}
}

func (x *ChatListResponse) GetChatList() []*ChatInfo {
	if x != nil {
		return x.ChatList
	}
	return nil
}

type ChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int32                  `protobuf:"varint,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryRequest) Reset() {
	*x = ChatHistoryRequest{}
	mi := &file_chatstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryRequest) ProtoMessage() {}

func (x *ChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*ChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{5}
}

func (x *ChatHistoryRequest) GetChatId() int32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type ChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*Message             `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatHistoryResponse) Reset() {
	*x = ChatHistoryResponse{}
	mi := &file_chatstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatHistoryResponse) ProtoMessage() {}

func (x *ChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*ChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{6}
}

func (x *ChatHistoryResponse) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ChatName      string                 `protobuf:"bytes,2,opt,name=chatName,proto3" json:"chatName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_chatstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{7}
}

func (x *CreateChatRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateChatRequest) GetChatName() string {
	if x != nil {
		return x.ChatName
	}
	return ""
}

type OperationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_chatstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chatstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_chatstream_proto_rawDescGZIP(), []int{8}
}

func (x *OperationStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_chatstream_proto protoreflect.FileDescriptor

const file_chatstream_proto_rawDesc = "" +
	"\n" +
	"\x10chatstream.proto\x12\n" +
	"chatstream\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\aMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\xb4\x01\n" +
	"\fMessageTable\x12\x1a\n" +
	"\bsenderID\x18\x01 \x01(\rR\bsenderID\x12&\n" +
	"\x0esenderUsername\x18\x02 \x01(\tR\x0esenderUsername\x12\x16\n" +
	"\x06chatID\x18\x03 \x01(\rR\x06chatID\x12\x18\n" +
	"\aMessage\x18\x04 \x01(\tR\aMessage\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\">\n" +
	"\bChatInfo\x12\x16\n" +
	"\x06chatID\x18\x01 \x01(\rR\x06chatID\x12\x1a\n" +
	"\bchatName\x18\x02 \x01(\tR\bchatName\"\x11\n" +
	"\x0fChatListRequest\"D\n" +
	"\x10ChatListResponse\x120\n" +
	"\bChatList\x18\x01 \x03(\v2\x14.chatstream.ChatInfoR\bChatList\",\n" +
	"\x12ChatHistoryRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\x05R\x06chatId\"D\n" +
	"\x13ChatHistoryResponse\x12-\n" +
	"\ahistory\x18\x01 \x03(\v2\x13.chatstream.MessageR\ahistory\"G\n" +
	"\x11CreateChatRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\bchatName\x18\x02 \x01(\tR\bchatName\")\n" +
	"\x0fOperationStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xc2\x02\n" +
	"\vChatService\x12R\n" +
	"\x0fLoadChatHistory\x12\x1e.chatstream.ChatHistoryRequest\x1a\x1f.chatstream.ChatHistoryResponse\x12G\n" +
	"\x0eProcessMessage\x12\x18.chatstream.MessageTable\x1a\x1b.chatstream.OperationStatus\x12K\n" +
	"\rCreateNewChat\x12\x1d.chatstream.CreateChatRequest\x1a\x1b.chatstream.OperationStatus\x12I\n" +
	"\fLoadChatList\x12\x1b.chatstream.ChatListRequest\x1a\x1c.chatstream.ChatListResponseB\x0eZ\f.;chatstreamb\x06proto3"

var (
	file_chatstream_proto_rawDescOnce sync.Once
	file_chatstream_proto_rawDescData []byte
)

func file_chatstream_proto_rawDescGZIP() []byte {
	file_chatstream_proto_rawDescOnce.Do(func() {
		file_chatstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatstream_proto_rawDesc), len(file_chatstream_proto_rawDesc)))
	})
	return file_chatstream_proto_rawDescData
}

var file_chatstream_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chatstream_proto_goTypes = []any{
	(*Message)(nil),               // 0: chatstream.Message
	(*MessageTable)(nil),          // 1: chatstream.MessageTable
	(*ChatInfo)(nil),              // 2: chatstream.ChatInfo
	(*ChatListRequest)(nil),       // 3: chatstream.ChatListRequest
	(*ChatListResponse)(nil),      // 4: chatstream.ChatListResponse
	(*ChatHistoryRequest)(nil),    // 5: chatstream.ChatHistoryRequest
	(*ChatHistoryResponse)(nil),   // 6: chatstream.ChatHistoryResponse
	(*CreateChatRequest)(nil),     // 7: chatstream.CreateChatRequest
	(*OperationStatus)(nil),       // 8: chatstream.OperationStatus
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_chatstream_proto_depIdxs = []int32{
	9, // 0: chatstream.Message.time:type_name -> google.protobuf.Timestamp
	9, // 1: chatstream.MessageTable.time:type_name -> google.protobuf.Timestamp
	2, // 2: chatstream.ChatListResponse.ChatList:type_name -> chatstream.ChatInfo
	0, // 3: chatstream.ChatHistoryResponse.history:type_name -> chatstream.Message
	5, // 4: chatstream.ChatService.LoadChatHistory:input_type -> chatstream.ChatHistoryRequest
	1, // 5: chatstream.ChatService.ProcessMessage:input_type -> chatstream.MessageTable
	7, // 6: chatstream.ChatService.CreateNewChat:input_type -> chatstream.CreateChatRequest
	3, // 7: chatstream.ChatService.LoadChatList:input_type -> chatstream.ChatListRequest
	6, // 8: chatstream.ChatService.LoadChatHistory:output_type -> chatstream.ChatHistoryResponse
	8, // 9: chatstream.ChatService.ProcessMessage:output_type -> chatstream.OperationStatus
	8, // 10: chatstream.ChatService.CreateNewChat:output_type -> chatstream.OperationStatus
	4, // 11: chatstream.ChatService.LoadChatList:output_type -> chatstream.ChatListResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_chatstream_proto_init() }
func file_chatstream_proto_init() {
	if File_chatstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatstream_proto_rawDesc), len(file_chatstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatstream_proto_goTypes,
		DependencyIndexes: file_chatstream_proto_depIdxs,
		MessageInfos:      file_chatstream_proto_msgTypes,
	}.Build()
	File_chatstream_proto = out.File
	file_chatstream_proto_goTypes = nil
	file_chatstream_proto_depIdxs = nil
}
